server {
    listen 80;
    listen 443 ssl;
    index index.php index.html;
    root /var/www/public;

    ssl_certificate /etc/nginx/ssl/fullchain1.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey1.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;

    server_name home.alfasolucoes.cloud;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
        fastcgi_param HTTP_HOST $host;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;
        fastcgi_param HTTPS on;
    }

    location ~ /\.ht {
        deny all;
    }
}

server {
    listen 80;
    return 301 https://$host$request_uri;
}
